# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

Run the following cell.

If you have anaconda installed, NumPy will be probably already installed.

In [1]:
! pip install numpy

Defaulting to user installation because normal site-packages is not writeable


## Using NumPy

Once you've installed NumPy you can import it as a library:

In [2]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [3]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_tup = (1,2,3)
my_tup

(1, 2, 3)

In [6]:
np.array(my_tup)

array([1, 2, 3])

In [7]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones(3)

array([1., 1., 1.])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [15]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [16]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [17]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
arr[0]

array([1., 0., 0.])

In [21]:
type(arr[0])

numpy.ndarray

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [22]:
np.random.rand(5)

array([0.30511546, 0.12922592, 0.67843918, 0.62818474, 0.15462722])

In [23]:
np.random.rand(5,5)

array([[0.05490892, 0.48428306, 0.42729689, 0.74889179, 0.16098655],
       [0.45716205, 0.10647954, 0.69730702, 0.52547076, 0.93251524],
       [0.46423698, 0.95562789, 0.97544619, 0.49884457, 0.06672927],
       [0.30240741, 0.89072191, 0.74758322, 0.05564336, 0.97373418],
       [0.7264692 , 0.50160948, 0.31305729, 0.08587084, 0.03275391]])

In [24]:
np.random.rand(3,3,3)

array([[[0.3286691 , 0.39762272, 0.41789835],
        [0.96227538, 0.2563194 , 0.83428874],
        [0.27595828, 0.00658525, 0.21932758]],

       [[0.93398679, 0.65492437, 0.10979519],
        [0.9048245 , 0.42117322, 0.68208611],
        [0.88281442, 0.8421934 , 0.74164988]],

       [[0.80281025, 0.78718817, 0.1791236 ],
        [0.43348835, 0.33777535, 0.58626811],
        [0.88425679, 0.05331118, 0.10832983]]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [25]:
np.random.randn(2)

array([-0.9173683 ,  0.73490014])

In [26]:
np.random.randn(5,5)

array([[ 2.23217394,  0.16152843,  0.55465349, -1.70160083,  0.89793316],
       [ 0.46804841,  0.19653454,  0.93249533, -0.66656902, -1.7190965 ],
       [-0.98570327,  1.06843976,  1.22038294, -0.40969207, -2.60307605],
       [-1.61045985, -0.31385096, -0.37747093,  0.41544044,  0.40305684],
       [-0.20820754,  0.21383564, -0.29939889, -1.8808939 , -0.15778726]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [27]:
np.random.randint(1,100)

90

In [28]:
np.random.randint(1,100,10)

array([82, 83, 28, 29, 88, 52, 53, 19, 50, 80])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [29]:
arr = np.arange(25)

ranarr = np.random.randint(0,50,10)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
ranarr

array([16, 49, 11, 11, 20, 40, 45,  7, 40, 36])

## Reshape
Returns an array containing the same data with a new shape.

In [32]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
arr.reshape(5,3)

ValueError: cannot reshape array of size 25 into shape (5,3)

why? Becuase 5 x 3 = 15 and we have 25 values, so they cannot fit into 5x3 matrix

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [34]:
ranarr

array([16, 49, 11, 11, 20, 40, 45,  7, 40, 36])

In [35]:
ranarr.max()

49

In [36]:
ranarr.argmax()

1

In [37]:
ranarr.min()

7

In [38]:
ranarr.argmin()

7

## Shape

Shape is an attribute that arrays have (not a method):

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
# Vector
arr.shape

(25,)

In [41]:
np.array([arr])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [42]:
np.array([arr]).shape

(1, 25)

In [43]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
arr.reshape(5,5).shape

(5, 5)

In [45]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [46]:
arr.reshape(1,25).shape

(1, 25)

In [47]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [48]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [50]:
arr.dtype

dtype('int32')

# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [51]:
#Creating sample array
arr = np.arange(0,11)

In [52]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [53]:
#Get a value at an index
arr[8]

8

In [54]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [55]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [58]:
l = [0,1,2,3,4,5,6,7,8,9]
l[0:5] = 100

TypeError: can only assign an iterable

In [65]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [67]:
#Change Slice
slice_of_arr[:] = 99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [68]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [69]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [70]:
arr = np.ones((2,2))
arr

array([[1., 1.],
       [1., 1.]])

In [71]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [72]:
import copy

cop = copy.deepcopy(arr)
cop

array([[1., 1.],
       [1., 1.]])

In [73]:
arr[0, 1] = 100
arr

array([[  1., 100.],
       [  1.,   1.]])

In [74]:
cop

array([[1., 1.],
       [1., 1.]])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [75]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [76]:
#Indexing row
arr_2d[1]


array([20, 25, 30])

In [77]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [78]:
# Getting individual element value
arr_2d[1,0]

20

In [83]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
#Shape bottom row
arr_2d[2]

In [82]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [ ]:
#Set up matrix
arr2d = np.zeros((10,10))
arr2d

In [ ]:
arr2d.shape

In [ ]:
#Length of array
arr_length = arr2d.shape[1]
arr_length

In [ ]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

Fancy indexing allows the following

In [ ]:
arr2d[[2,4,6, 8]]

In [ ]:
#Allows in any order
arr2d[[6,4,2,7]]

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [ ]:
arr = np.arange(1,11)
arr

In [ ]:
arr > 4

In [ ]:
bool_arr = arr > 4

In [ ]:
bool_arr

In [ ]:
arr[bool_arr]

In [ ]:
arr[arr > 2]

In [ ]:
x = 2

arr[arr > x]

# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [ ]:
arr = np.arange(0,10)
arr

In [ ]:
arr + arr

In [ ]:
arr + [1,2,3]

In [ ]:
# list merges upon addition

[1,2,3] + [1,2,3]

In [ ]:
[1,2,3] * [1,2,3]

In [ ]:
[1,2,3] - [1,2,3]

In [ ]:
arr * arr

In [ ]:
arr - arr

In [ ]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

In [ ]:
arr

In [ ]:
# Also warning, but not an error instead infinity
1/arr

In [ ]:
arr**3

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [ ]:
arr ** 0.5

In [ ]:
#Taking Square Roots
np.sqrt(arr)

In [ ]:
#Calcualting exponential (e^)
np.exp(arr)

In [ ]:
np.max(arr) #same as arr.max()

In [ ]:
np.sin(arr)

In [ ]:
np.log(arr)

# Great Job!

That's all we need to know for now!